# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Avoid interactive
ENV DEBIAN_FRONTEND=noninteractive

# Upgrade pip
RUN pip install --no-cache-dir --disable-pip-version-check --upgrade pip

# Install dependencies
RUN pip install --no-cache-dir --disable-pip-version-check mcp requests pydantic

# Set working directory
WORKDIR /app

# Copy code
COPY server.py /app/server.py

# Unbuffered stdout/stderr
ENV PYTHONUNBUFFERED=1

# Default command
CMD ["python", "server.py"]
